#!/usr/bin/python
#    HAL userspace component to interface with Arduino board
#    by Colin Kingsbury (http://ckcnc.wordpress.com_)
#    Inspired by the earlier example from Jeff Epler
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
import serial
import hal
import sys
import time

#First we open the serial port. This should correspond to the port the Arduino
#is connected to. This can be found in the Arduino IDE in Tools->Serial Port
PORT = "/dev/ttyACM0"
ser = serial.Serial(PORT, 38400, timeout=15)

#Now we create the HAL component and its pins
c = hal.component("arduino")
c.newpin("switch-on",hal.HAL_BIT,hal.HAL_IN)
c.newpin("switch-off",hal.HAL_BIT,hal.HAL_IN)
c.newpin("machine-state",hal.HAL_BIT,hal.HAL_IN)
c.newpin("axis0-cmd",hal.HAL_FLOAT,hal.HAL_IN)
c.newpin("axis1-cmd",hal.HAL_FLOAT,hal.HAL_IN)
c.newpin("axis2-cmd",hal.HAL_FLOAT,hal.HAL_IN)
c.newpin("axis3-cmd",hal.HAL_FLOAT,hal.HAL_IN)
c.newpin("xMinLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("yMinLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("zMinLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("aMinLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("xMaxLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("yMaxLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("zMaxLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("aMaxLmt",hal.HAL_BIT,hal.HAL_IN)
c.newpin("xHome",hal.HAL_BIT,hal.HAL_IN)
c.newpin("yHome",hal.HAL_BIT,hal.HAL_IN)
c.newpin("zHome",hal.HAL_BIT,hal.HAL_IN)
c.newpin("aHome",hal.HAL_BIT,hal.HAL_IN)
time.sleep(2)
c.ready()

#We save the machine state (i.e. whether it's off or on) so that we only
#send a message to the Arduino when it changes
machineState = c['machine-state']
axis0cmd = c['axis0-cmd']
axis1cmd = c['axis1-cmd']
axis2cmd = c['axis2-cmd']
axis3cmd = c['axis3-cmd']
#c['xMinLmt'] = 1
#c['xMaxLmt'] = 1
#c['yMinLmt'] = 1
#c['yMaxLmt'] = 1
#c['zMinLmt'] = 1
#c['zMaxLmt'] = 1
#c['aMinLmt'] = 1
#c['aMaxLmt'] = 1
#Check if the machine is on and set the LED accordingly
if(machineState != 1):
  ser.write("+R")

axis0cmdOld = 0;
axis1cmdOld = 0;
axis2cmdOld = 0;
axis3cmdOld = 0;

try:
  while 1:
    ser.write("jog c;\n");
    time.sleep(.001)

    axis0cmd = c['axis0-cmd'];
    if axis0cmd != axis0cmdOld:
      axis0cmdOld = axis0cmd;
      axis0icmd = c['axis0-cmd'] * 1000000
      ser.write("jog X");
      ser.write(repr(axis0icmd))
      ser.write(";");
      ser.write("\n");
#      time.sleep(.001)

    axis1cmd = c['axis1-cmd'];
    if axis1cmd != axis1cmdOld:
      axis1cmdOld = axis1cmd;
      axis1icmd = c['axis1-cmd'] * 1000000
      ser.write("jog Y");
      ser.write(repr(axis1icmd))
      ser.write(";");
      ser.write("\n");
#      time.sleep(.001)

    axis2cmd = c['axis2-cmd'];
    if axis2cmd != axis2cmdOld:
      axis2cmdOld = axis2cmd;
      axis2icmd = c['axis2-cmd'] * 1000000
      ser.write("jog Z");
      ser.write(repr(axis2icmd))
      ser.write(";");
      ser.write("\n");
#      time.sleep(.001)

    axis3cmd = c['axis3-cmd'];
    if axis3cmd != axis3cmdOld:
      axis3cmdOld = axis3cmd;
      axis3icmd = c['axis3-cmd'] * 1000000
      ser.write("jog A");
      ser.write(repr(axis3icmd))
      ser.write(";");
      ser.write("\n");
#      time.sleep(.001)

    #Check the machine State
    if(machineState != c['machine-state']):
      if(c['machine-state'] == 1):
        #The machine is on, so turn on the green LED and turn off the red one
        ser.write("+G")
        ser.write("-R")
#        time.sleep(.001)

      else:
        #opposite of above
        ser.write("-G")
        ser.write("+R")
#        time.sleep(.001)
      #update the machine state variable
      machineState = c['machine-state']
    #Check to see if we have a message waiting from the Arduino
    while ser.inWaiting():
      #This should be set to the length of whatever fixed-length message
      #you're sending from the arduino. It does not have to be the same length
      #as the outbound messages.
      key = ser.read(2)
      #The Arduino generates two different key events
      #One when the key is pressed down (+S) and another when it is released (-S)
      #In this case we are going to ignore the release

# Set min limit triggers
      if(key == "x0"):
        c['xMinLmt'] = 1
      if(key == "y0"):
        c['yMinLmt'] = 1
      if(key == "z0"):
        c['zMinLmt'] = 1
      if(key == "a0"):
        c['aMinLmt'] = 1

# Clear limit triggers
      if(key == "x1"):
        c['xMinLmt'] = 0
        c['xMaxLmt'] = 0
      if(key == "y1"):
        c['yMinLmt'] = 0
        c['yMaxLmt'] = 0
      if(key == "z1"):
        c['zMinLmt'] = 0
        c['zMaxLmt'] = 0
      if(key == "a1"):
        c['aMinLmt'] = 0
        c['aMaxLmt'] = 0

# Set max limit triggers
      if(key == "x2"):
        c['xMaxLmt'] = 1
      if(key == "y2"):
        c['yMaxLmt'] = 1
      if(key == "z2"):
        c['zMaxLmt'] = 1
      if(key == "a2"):
        c['aMaxLmt'] = 1

# set home switches
      if(key == "x4"):
        c['xHome'] = 0
      if(key == "y4"):
        c['yHome'] = 0
      if(key == "z4"):
        c['zHome'] = 0
      if(key == "a4"):
        c['aHome'] = 0

# unset home switches
      if(key == "x5"):
        c['xHome'] = 1
      if(key == "y5"):
        c['yHome'] = 1
      if(key == "z5"):
        c['zHome'] = 1
      if(key == "a5"):
        c['aHome'] = 1

      if(key == "+S"):
        #If the machine is currently on, we turn it off, and vice-versa
        if(machineState == 1):
          c['switch-on'] = 0
          c['switch-off'] = 1
        else:
          c['switch-on'] = 1
          c['switch-off'] = 0


except KeyboardInterrupt:
    ser.write("-R-G");
    raise SystemExit

